<?php

namespace CatalogBundle\Repository;

/**
 * EstateMediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstateMediaRepository extends \Doctrine\ORM\EntityRepository
{
}
