<?php

namespace CatalogBundle\Repository;

/**
 * SystemParameterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemParameterRepository extends \Doctrine\ORM\EntityRepository
{
}
