security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        in_memory:
            memory: ~
        fos_userbundle:
#            id: fos_user.user_provider.username
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            logout:
                path: fos_user_security_logout
                target: mainpage
            anonymous:    true

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/(%languages%)/user/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(%languages%)/user/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(%languages%)/user/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/(%languages%)/admin/.*, role: ROLE_ADMIN }
        - { path: ^/(%languages%)/cabinet/.*, role: IS_AUTHENTICATED_REMEMBERED }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN