<?php

namespace UserBundle\Repository;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**@var \FOS\UserBundle\Util\Canonicalizer*/
    private $canonicalizer;

    private function setCanonicalizer($canonicalizer) {
        $this->canonicalizer = $canonicalizer;
    }

    public function findByEmail($email) {
        return $this->findOneByEmailCanonical(
            $this->canonicalizer->canonicalize($email)
        );
    }

}
